### PR TITLE
Update plugin2.ts

### PR DESCRIPTION
**Pull request by guest271314**

### CODE REVIEW

**Comment by TomasHubelbauer** [comment]
This repro uses hard-coded names, but the point is the desired mechanism should be dynamic. I can't use `build.module` because it takes an exact module name. `test:anything` should work. Thanks for the PR, but this is not the solution I am after.

**Comment by guest271314** [comment]
>  I can't use `build.module` because it takes an exact module name. `test:anything` should work. 

At some point you are going to have to resolve `"test:*"`  to a relative or absolute path, so there is no escaping hardcoding the module path in all cases.

**Comment by TomasHubelbauer** [comment]
Bun has a concept of virtual modules which do not have to be backed by paths, just content. 

https://bun.sh/docs/runtime/plugins#virtual-modules

There is no need to involve the file system.

**Comment by guest271314** [comment]
Need more information about exactly what you are doing. Neither Node.js' loader system nor Bun's plugin system  nor a `RegExp` is going to help you in this case.

From what I read you are eventually getting some dynamic specifier in the form of `"specifier:"` - at runtime. Alright. Assuming there is more than one (1) path to follow, meaning more than one (1) file that will be imported, you are going to have to know where to get the content from. 

I don't think you are looking for `onResolve` with a `RegExp` of just beginning with `"demo:"`. That is not going to help you at all if there is more than one (1) path, e.g., `"demo:1"`, `"demo:b"`. You still have to know which specifiers to map to `file:` or `https:`, or whatever other protocol is used.

**Pull request closed without merging**
